### PR TITLE
Add grad student profile for Antero.

### PR DESCRIPTION
**Pull request by a2379**
Will update photo and specific research area later.

### CODE REVIEW

**Comment by ahuoguo** [comment]
will merge once you have the photo

**Comment by a2379** [comment]
Updated blank photos to the Jumbo logo, looks a little nicer now IMO.

**Comment by a2379** [comment]
@ahuoguo I think Jasper's email is wrong, it says the domain is gmail.edu, not sure if it's supposed to be gmail or tufts.edu.

**Comment by ahuoguo** [comment]
Thanks for the catch!

**Pull request merged**
